version : "3"
services:
  #mariadb container
  mariadb:
    container_name: "mariadb"
    build: /requirements/mariadb
    ports:
      - "3306:9000"
    env_file:
      - /requirements/mariadb/.env
    volumes:
      -mariadb:/var/lib/mysql
    restart: always
  #wordpress container
  wordpress:
    depends_on: -mariadb
    container_name: "wordpress"
    build: /SRC/wordpress
    ports:
      - "9000:443"
    env_file:
      - /requirements/wordpress/.env
    volumes:
      - wordpress:/var/www/html/:ro
    restart: always
  #nginx container
  nginx:
    depends_on: -wordpress
    container-name : "Nginx"
    build: /SRC/nginx
    ports: 
      - "443:443"
    volumes:
      - wordpress:/var/www/html/:ro
    restart: always
volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './'
  mariadb: