version : "3"
#containers 
services:
  #mariadb container
  mariadb:
    build:
      context: ${PWD}/requirements/mariadb/
      dockerfile: ${PWD}/requirements/mariadb/Dockerfile
      args:
        - DB_NAME
        - MYSQL_USER
        - MYSQL_PASSWORD
        - MYSQL_ROOT_PASSWORD
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql/
    networks:
      - net
  #wordpress container
  wordpress:
    depends_on:
      - mariadb
    build: 
      context: ${PWD}/requirements/wordpress/
      args:
        - DB_NAME
        - DB_USER
        - DB_PASSWORD
        - DB_HOST
        - admin_email
        - admin_user
        - admin_password
        - title
    container_name: wordpress
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html/
    networks:
      - net
  #nginx container
  nginx:
    depends_on:
      - wordpress
      - glances
    build: ${PWD}/requirements/ngnix/
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html/
    networks:
      - net
    restart: unless-stopped
  #redis container
  redis :
    container_name : redis
    build : ${PWD}/requirements/bonus/redis
    networks:
      - net
  #adminer
  adminer:
    depends_on:
      - mariadb
    container_name: adminer
    build: ${PWD}/requirements/bonus/adminer
    networks:
      - net
  #website
  website:
    container_name: website
    build : ${PWD}/requirements/bonus/website
    networks:
      - net
  #glances
  glances:
    container_name: glances
    build : ${PWD}/requirements/bonus/glances
    networks:
      - net
    volumes:
      - /goinfre/tchtaibi/docker/.docker/run/docker.sock:/var/run/docker.sock:ro
    restart: always
    pid: "host"
#volumes 
volumes:
  #wordpress volume
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/tools/volume/wordpress
  #mariadb volume
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/tools/volume/db
#networks 
networks:
  net:
    driver: bridge