version : "3"
#containers 
services:
  #mariadb container
  mariadb:
    build:
      dockerfile: ${PWD}/requirements/mariadb/Dockerfile
      args:
        - DB_NAME
        - MYSQL_ROOT_USER
        - MYSQL_PASSWORD
        - MYSQL_ROOT_PASSWORD
    container_name: mariadb
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql/
    networks:
      - net
  #wordpress container
  wordpress:
    depends_on:
      - mariadb
    build: 
      context: ${PWD}/requirements/wordpress/
      args:
        - DB_NAME
        - DB_USER
        - DB_PASSWORD
        - DB_HOST
        - admin_email
        - admin_user
        - admin_password
        - title
    container_name: wordpress
    ports:
      - "9000:9000"
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html/
    networks:
      - net
  #nginx container
  nginx:
    depends_on:
      - wordpress
    build: ${PWD}/requirements/ngnix/
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html/
    networks:
      - net
    restart: unless-stopped
#volumes 
volumes:
  #wordpress volume
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/tools/volume/wordpress
  #mariadb volume
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/tools/volume/db
#networks 
networks:
  net:
    driver: bridge